Large Flask Application/Solution/models.py
# set up db inside the __init__.py under solution folder
from Solution import db

class Puppies(db.Model):

    __tablename__ = "puppies"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)

    owner = db.relationship('Owners', backref='Puppies', uselist=False)

    def __init__(self, name) -> None:
        self.name = name

    def __repr__(self) -> str:
        if self.owner:
            return f"Puppy name is {self.name} and owner is {self.owner.name}"
        else:
            return f"Puppy name is {self.name} and has not owner yet"

class Owners(db.Model):
    __tablename__ = "owners"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)

    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self, name, puppy_id) -> None:
        self.name = name
        self.puppy_id = puppy_id

Large Flask Application/Solution/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField("Owner Name:")
    id = IntegerField("Puppy ID:")
    submit = SubmitField("Add Owner")

Large Flask Application/Solution/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField("Name of Puppy:")
    submit = SubmitField("Add Puppy")

class DelForm(FlaskForm):

    id = IntegerField("Id Number of Puppy to Remove")
    submit = SubmitField("Remove Puppy")

Large Flask Application/Solution/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SECRET_KEY'] = "mysecret"

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)

from Solution.owners.views import owner_blueprint
from Solution.puppies.views import puppy_blueprint

app.register_blueprint(owner_blueprint, url_prefix='/owners')
app.register_blueprint(puppy_blueprint, url_prefix='/puppies')

Large Flask Application/Solution/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from Solution import db
from Solution.models import Owners
from Solution.owners.forms import AddForm

owner_blueprint = Blueprint("owners", __name__, template_folder='templates/owner')

@owner_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        id = form.id.data

        new_owner = Owners(name, id)
        db.session.add(new_owner)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('add.html', form = form)

Large Flask Application/Solution/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for
from Solution import db
from Solution.models import Puppies
from Solution.puppies.forms import AddForm, DelForm

puppy_blueprint = Blueprint("puppies", __name__, template_folder='templates/puppies')

@puppy_blueprint.route('/add', methods=['GET', 'POST'])
def add():

    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data

        new_pup = Puppies(name)
        db.session.add(new_pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('add.html', form=form)

@puppy_blueprint.route('/list', methods=['GET', 'POST'])
def list():

    puppies = Puppies.query.all()

    return render_template('list.html', puppies=puppies)

@puppy_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():

    form = DelForm()
    if form.validate_on_submit():

        id = form.id.data

        pup = Puppies.query.get(id)
        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('delete.html', form=form)

Large Flask Application/Solution/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{{url_for('index')}}">Home</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.add')}}">Add Puppy</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.delete')}}">Delete Puppy</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.list')}}">List of Puppies</a>
            <a class="nav-item nav-link" href="{{url_for('owners.add')}}">Add Owner</a>
          </div>
    </nav>
 
    {% block content %}

    {% endblock %}


</body>
</html>

Large Flask Application/Solution/templates/home.html
{% extends "base.html" %}

{% block content %}

<div class="h-100 p-5 text-white bg-dark rounded-3">
  <h1>Welcome to our adoption page</h1>
  <p>Please select one of the link from the nav bar</p>
</div>

{% endblock %}